---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 黄吉祥.
--- DateTime: 2023/2/16 15:49
---
--获取锁中的线程表示
local id=redis.call('get',KEYS[1])
--比较线程标识与锁中的标识是否一致
if(id==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0